spring:
  profiles:
    active: prod
  config:
    location: classpath:config/
  application:
    name: gilbert-api-elasticsearch
  elasticsearch:  
    cluster-name: dev-application
    cluster-nodes: 10.110.10.27:9300
    username: elastic        
    password: changeme
    
server: 
  port: 8080
